### ISSUE TITLE
Exception: SharedItemStateManager cannot be cast to HippoSharedItemStateManager

### ISSUE THREAD

**Issue by jpierson** [woonsanko/hippo-db-migration-demo#1]
As part of a an test run of these migration steps on a mostly empty project generated from the default HippoCMS v12 archetype we ran into the following error when running the migrate step. 

```
Exception in thread "main" java.lang.ClassCastException: org.apache.jackrabbit.core.state.SharedItemStateManager cannot be cast to org.hippoecm.repository.jackrabbit.HippoSharedItemStateManager
        at org.hippoecm.repository.FacetedNavigationEngineImpl.doInit(FacetedNavigationEngineImpl.java:655)
        at org.apache.jackrabbit.core.query.AbstractQueryHandler.init(AbstractQueryHandler.java:78)
        at org.apache.jackrabbit.core.config.RepositoryConfigurationParser$1.getQueryHandler(RepositoryConfigurationParser.java:683)
        at org.apache.jackrabbit.core.config.WorkspaceConfig.getQueryHandler(WorkspaceConfig.java:251)
        at org.apache.jackrabbit.core.SearchManager.<init>(SearchManager.java:171)
        at org.apache.jackrabbit.core.RepositoryImpl$WorkspaceInfo.getSearchManager(RepositoryImpl.java:1902)
        at org.apache.jackrabbit.core.RepositoryImpl$WorkspaceInfo.doPostInitialize(RepositoryImpl.java:2140)
        at org.apache.jackrabbit.core.RepositoryImpl$WorkspaceInfo.initialize(RepositoryImpl.java:2038)
        at org.apache.jackrabbit.core.RepositoryImpl.initStartupWorkspaces(RepositoryImpl.java:544)
        at org.apache.jackrabbit.core.RepositoryImpl.<init>(RepositoryImpl.java:327)
        at org.apache.jackrabbit.core.RepositoryImpl.create(RepositoryImpl.java:616)
        at org.apache.jackrabbit.core.RepositoryCopier.copy(RepositoryCopier.java:148)
        at org.apache.jackrabbit.core.RepositoryCopier.copy(RepositoryCopier.java:112)
        at org.apache.jackrabbit.standalone.Main.backup(Main.java:248)
        at org.apache.jackrabbit.standalone.Main.run(Main.java:172)
        at org.apache.jackrabbit.standalone.Main.main(Main.java:59)
```

Our test case is migrating from a basic H2 setup with the mostly empty v12 instance of HippoCMS over to one that has been configured locally to run with Postgres through cargo. The eventual goal is to model these same steps to perform a MySQL to Postgres conversion once we get our footing with a simple scenario.

While just a guess at this point I'm wondering if the error has something to do with our choice when selecting "best compatible version which you can download" as we did in step 4. In our case we went for [jackrabbit-standalone-2.20.2.jar](https://www.apache.org/dyn/closer.lua/jackrabbit/2.20.2/jackrabbit-standalone-2.20.2.jar) but perhaps that's not correct for HippoCMS v12?

Another detail is that the target Postgres database has been created and stood up using the same empty v12 project with just the connection details modified to work with Postgres. We've confirmed that the site appears to be working correctly with cargo but the backup/target database in this case is not empty because we've already initialized it by running the project with cargo pointing to the DB. It wasn't clear from the steps whether the database should be empty or have an initial schema already created.

**Comment by jpierson** [comment]
Sorry, filed in the wrong repo. Moved over to https://github.com/woonsanko/recipe-for-hippo-db-migration/issues/1https://github.com/woonsanko/recipe-for-hippo-db-migration/issues/1.
